/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;

import javax.swing.JList;
import javax.swing.JOptionPane;

import mundo.Producto;

/**
 *
 * @author daniel
 */
public class DialogoInventario extends javax.swing.JDialog {
	InterfazPrincipal principal;

	/**
	 * Creates new form DialogoInventario
	 */
	public DialogoInventario(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		principal = (InterfazPrincipal) parent;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		setTitle("Inventario");
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		listaInventario = new javax.swing.JList<>();
		jLabel4 = new javax.swing.JLabel();
		labNombre = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		labMarca = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		labValor = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		labTalla = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		labColor = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtReferencia = new javax.swing.JTextField();
		btnBuscar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		actualizarLista();
		listaInventario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		listaInventario.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				listaInventarioValueChanged(evt);
			}
		});
		
		actualizarInfo();
		
		jScrollPane1.setViewportView(listaInventario);

		jLabel4.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel4.setText("Nombre:");

		labNombre.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

		jLabel5.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel5.setText("Marca:");

		labMarca.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

		jLabel6.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel6.setText("Valor:");

		labValor.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

		jLabel7.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel7.setText("Talla:");

		labTalla.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

		jLabel8.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel8.setText("Color:");

		labColor.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

		jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
		jLabel1.setText("Descripcion");

		jLabel2.setText("Referencia:");

		btnBuscar.setText("Buscar");
		btnBuscar.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				btnBuscarActionPerformed(arg0);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
												jPanel1Layout
														.createSequentialGroup()
														.addComponent(jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 277,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addGap(54, 54, 54)
																		.addGroup(jPanel1Layout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(jLabel5)
																				.addComponent(jLabel4)
																				.addComponent(jLabel6)
																				.addComponent(jLabel7)
																				.addComponent(jLabel8))
																		.addGap(26, 26, 26)
																		.addGroup(jPanel1Layout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(labMarca)
																				.addComponent(labNombre)
																				.addComponent(labValor)
																				.addComponent(labTalla)
																				.addComponent(labColor)))
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addGap(40, 40, 40).addComponent(jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				159,
																				javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE,
														138, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnBuscar)))
								.addContainerGap(62, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(10, 10, 10).addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
								.addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnBuscar))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
																36, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel4).addComponent(labNombre))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel5).addComponent(labMarca))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel6).addComponent(labValor))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel7).addComponent(labTalla))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel8).addComponent(labColor))
														.addGap(0, 77, Short.MAX_VALUE))
												.addComponent(jScrollPane1))
								.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void btnBuscarActionPerformed(ActionEvent arg0) {
		try{
			listaInventario.setSelectedIndex(principal.buscarItem(txtReferencia.getText()));
			actualizarInfo();
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(this, e.getMessage());
		}
	}

	private void actualizarLista() {
		listaInventario = new JList(principal.controller.darInventario().toArray());
		listaInventario.setSelectedIndex(0);
		actualizarInfo();
	}

	private void listaInventarioValueChanged(javax.swing.event.ListSelectionEvent evt) {
		
		actualizarInfo();
	}
	private void actualizarInfo(){
		if(principal.controller.darInventario().size()>0){
			Producto i = listaInventario.getSelectedValue();
			labColor.setText(i.darColor());
			labMarca.setText(i.darMarca());
			labNombre.setText(i.darNombre());
			labTalla.setText(i.darTalla());
			labValor.setText(i.darPrecioVenta()+"");
			repaint();
		}
	}
	

	// Variables declaration - do not modify
	private javax.swing.JButton btnBuscar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel labColor;
	private javax.swing.JLabel labMarca;
	private javax.swing.JLabel labNombre;
	private javax.swing.JLabel labTalla;
	private javax.swing.JLabel labValor;
	private javax.swing.JList<Producto> listaInventario;
	private javax.swing.JTextField txtReferencia;
	// End of variables declaration

}
