package interfaz;

import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

import controller.ClienteNoExisteException;
import mundo.Producto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author daniel
 */
public class DialogoVender extends javax.swing.JDialog {
	InterfazPrincipal principal;
	Producto seleccionado;
	ArrayList carrito;
	private JLabel jLabel9;
	private JLabel labCantidad;

	/**
	 * Creates new form DialogoVender
	 */
	public DialogoVender(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		principal = (InterfazPrincipal) parent;
		seleccionado = null;
		carrito = new ArrayList();
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        panelAgregar = new javax.swing.JPanel();
        txtReferencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labMarca = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labValor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labTalla = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labColor = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labCantidad = new javax.swing.JLabel();
        panelCarrito = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCarrito = new javax.swing.JList<>(new DefaultListModel<>());
        btnQuitar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        txtReferencia.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel1.setText("Referencia:");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel2.setText("Agregar producto");

        btnAgregar.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel4.setText("Nombre:");

        labNombre.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel5.setText("Marca:");

        labMarca.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel6.setText("Valor:");

        labValor.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel7.setText("Talla:");

        labTalla.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel8.setText("Color:");

        labColor.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jLabel9.setText("Cantidad:");

        labCantidad.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

        javax.swing.GroupLayout panelAgregarLayout = new javax.swing.GroupLayout(panelAgregar);
        panelAgregar.setLayout(panelAgregarLayout);
        panelAgregarLayout.setHorizontalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnAgregar))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarLayout.createSequentialGroup()
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)))
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAgregarLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labMarca)
                                            .addComponent(labNombre)
                                            .addComponent(labValor)
                                            .addComponent(labTalla)
                                            .addComponent(labColor)
                                            .addComponent(labCantidad)))
                                    .addGroup(panelAgregarLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscar))))
                            .addGroup(panelAgregarLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(52, 52, 52))
        );
        panelAgregarLayout.setVerticalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labTalla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(26, 26, 26))
        );

        jLabel3.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel3.setText("Carrito");

        listaCarrito.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        listaCarrito.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaCarrito.setToolTipText("");
        jScrollPane1.setViewportView(listaCarrito);

        btnQuitar.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        btnQuitar.setEnabled(false);

        btnComprar.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        btnComprar.setText("Comprar Todo");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        btnComprar.setEnabled(false);

        javax.swing.GroupLayout panelCarritoLayout = new javax.swing.GroupLayout(panelCarrito);
        panelCarrito.setLayout(panelCarritoLayout);
        panelCarritoLayout.setHorizontalGroup(
            panelCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarritoLayout.createSequentialGroup()
                .addGroup(panelCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCarritoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelCarritoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprar)))
                .addGap(39, 39, 39))
            .addGroup(panelCarritoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCarritoLayout.setVerticalGroup(
            panelCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarritoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitar)
                    .addComponent(btnComprar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>

	private void actualizarLista() {
		if (seleccionado != null && !carrito.contains(seleccionado)) {
			carrito.add(seleccionado);
		}
		DefaultListModel m = (DefaultListModel) listaCarrito.getModel();
		if (carrito.size() > 0 && !m.contains(seleccionado))
			m.addElement(carrito.get(carrito.size() - 1));
		listaCarrito.setModel(m);
		listaCarrito.setSelectedIndex(0);
	}
//Esto no esta muy bien implementado pero yolo
	private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			int c1 = seleccionado.darCantidad();
			int c =Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad a vender, actualmente "+seleccionado.darCantidad()));
			if(c>seleccionado.darCantidad()){
				JOptionPane.showMessageDialog(this, "No hay la cantidad de producto");
				return;
			}
			seleccionado = new Producto(seleccionado, c);
			actualizarLista();
			c1-=c;
			seleccionado = new Producto(seleccionado,c1);
			actualizarInfo();
			btnQuitar.setEnabled(true);
			btnComprar.setEnabled(true);
			if(c1==0)btnAgregar.setEnabled(false);
		} catch (NumberFormatException e) {
			
		}
	}

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {
		ArrayList<Producto> p = principal.controller.darInventario();
		for (int i = 0; i < p.size(); i++) {
			if (p.get(i).darReferencia().equalsIgnoreCase(txtReferencia.getText())) {
				seleccionado = p.get(i);
				actualizarInfo();
				btnAgregar.setEnabled(true);
				return;
			}
		}
		JOptionPane.showMessageDialog(this, "Esta referencia no pertenece a ningun objeto");
	}

	private void actualizarInfo() {
		labColor.setText(seleccionado.darColor());
		labMarca.setText(seleccionado.darMarca());
		labNombre.setText(seleccionado.darNombre());
		labTalla.setText(seleccionado.darTalla());
		labValor.setText(seleccionado.darPrecioVenta() + "");
		labCantidad.setText(seleccionado.darCantidad()+"");
		repaint();
	}

	private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {
		int in = listaCarrito.getSelectedIndex();
		DefaultListModel m = (DefaultListModel) listaCarrito.getModel();
		m.remove(in);
		listaCarrito.setModel(m);
	}

	private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {
		if (JOptionPane.showConfirmDialog(this, "Desea vender estos productos?") == JOptionPane.YES_OPTION) {
			boolean p = false;
			if (JOptionPane.showConfirmDialog(this, "El pago sera ahora?") == JOptionPane.YES_OPTION) {
				p = true;
			}
			try{
				long cCliente = Long.parseLong(JOptionPane.showInputDialog("Ingrese la cedula del cliente"));
				if(!principal.controller.darMundo().existeCliente(cCliente)){
					String nombres = "", apellidos="",direccion="";
					while(nombres==""||nombres.isEmpty()){
						 nombres= JOptionPane.showInputDialog("Ingrese los nombres del cliente");
					}
					while(apellidos ==""||apellidos.isEmpty()){
						apellidos = JOptionPane.showInputDialog("Ingrese los apellidos del cliente");
					}
					while(direccion==""||direccion.isEmpty()){
						direccion = JOptionPane.showInputDialog("Ingrese la direccion del cliente");
					}
					HashMap<String, String> hm = new HashMap<String,String>();
					hm.put("cedula", cCliente+"");
					hm.put("nombres", nombres);
					hm.put("direccion", direccion);
					principal.controller.darMundo().agregarCliente(hm);
				}
				ArrayList<Producto> vender = new ArrayList<Producto>();
				for (int i = 0; i < listaCarrito.getModel().getSize(); i++) {
					vender.add((Producto) listaCarrito.getModel().getElementAt(i));
				}
				principal.controller.vender(p, vender, cCliente);
			}
			catch(ClienteNoExisteException f){
				System.out.println("f");
			}
			catch(Exception e){
				JOptionPane.showMessageDialog(this, e.getCause()+", "+ e.getMessage());
				return;
			}
			
		}
		
		this.dispose();
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnAgregar;
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnComprar;
	private javax.swing.JButton btnQuitar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JLabel labColor;
	private javax.swing.JLabel labMarca;
	private javax.swing.JLabel labNombre;
	private javax.swing.JLabel labTalla;
	private javax.swing.JLabel labValor;
	private javax.swing.JList listaCarrito;
	private javax.swing.JPanel panelAgregar;
	private javax.swing.JPanel panelCarrito;
	private javax.swing.JTextField txtReferencia;
	// End of variables declaration
}
