package interfaz;

import java.awt.HeadlessException;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author daniel
 */
public class DialogoAgregarProducto extends javax.swing.JDialog {
	InterfazPrincipal principal;

	/**
	 * Creates new form DialogoAgregar
	 */
	public DialogoAgregarProducto(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		principal = (InterfazPrincipal) parent;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		panelDialogo = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		txtReferencia = new javax.swing.JTextField();
		txtNombre = new javax.swing.JTextField();
		txtTalla = new javax.swing.JTextField();
		txtMarca = new javax.swing.JTextField();
		txtTela = new javax.swing.JTextField();
		txtPrecioCompra = new javax.swing.JTextField();
		txtColor = new javax.swing.JTextField();
		txtPrecioVenta = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		btnAgregar = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		txtCantidad = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel1.setText("*Referencia:");

		jLabel2.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel2.setText("*Precio Venta:");

		jLabel3.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel3.setText("*Precio Compra:");

		jLabel4.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel4.setText("*Nombre:");

		jLabel5.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel5.setText("*Marca:");

		jLabel6.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel6.setText(" Talla:");

		jLabel7.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel7.setText(" Color:");

		jLabel8.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel8.setText(" Tela:");

		txtReferencia.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		txtReferencia.setToolTipText("");
		txtReferencia.setName("txtReferencia"); // NOI18N

		txtNombre.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		txtNombre.setToolTipText("");
		txtNombre.setName("txtReferencia"); // NOI18N

		txtTalla.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		txtTalla.setToolTipText("");
		txtTalla.setName("txtReferencia"); // NOI18N

		txtMarca.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		txtMarca.setToolTipText("");
		txtMarca.setName("txtReferencia"); // NOI18N

		txtTela.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		txtTela.setToolTipText("");
		txtTela.setName("txtReferencia"); // NOI18N

		txtPrecioCompra.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		txtPrecioCompra.setToolTipText("");
		txtPrecioCompra.setName("txtReferencia"); // NOI18N

		txtColor.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		txtColor.setToolTipText("");
		txtColor.setName("txtReferencia"); // NOI18N

		txtPrecioVenta.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		txtPrecioVenta.setToolTipText("");
		txtPrecioVenta.setName("txtReferencia"); // NOI18N

		jLabel9.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
		jLabel9.setText("Agrega un producto");

		btnAgregar.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		btnAgregar.setText("Agregar");
		btnAgregar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAgregarActionPerformed(evt);
			}
		});

		jLabel10.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		jLabel10.setText("*Cantidad:");

		txtCantidad.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		txtCantidad.setToolTipText("");
		txtCantidad.setName("txtCantidad"); // NOI18N

		javax.swing.GroupLayout panelDialogoLayout = new javax.swing.GroupLayout(panelDialogo);
		panelDialogo.setLayout(panelDialogoLayout);
		panelDialogoLayout.setHorizontalGroup(panelDialogoLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panelDialogoLayout.createSequentialGroup().addContainerGap()
						.addGroup(panelDialogoLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										panelDialogoLayout.createSequentialGroup().addComponent(jLabel10)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(panelDialogoLayout.createSequentialGroup().addComponent(jLabel7)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										panelDialogoLayout.createSequentialGroup().addComponent(jLabel6)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										panelDialogoLayout.createSequentialGroup().addComponent(jLabel8)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtTela, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										panelDialogoLayout.createSequentialGroup().addComponent(jLabel5)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										panelDialogoLayout.createSequentialGroup().addComponent(jLabel3)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE,
														191, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										panelDialogoLayout.createSequentialGroup().addComponent(jLabel4)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDialogoLayout
										.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addGroup(panelDialogoLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDialogoLayout
														.createSequentialGroup().addComponent(jLabel2)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(txtPrecioVenta,
																javax.swing.GroupLayout.PREFERRED_SIZE, 191,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														panelDialogoLayout.createSequentialGroup().addComponent(jLabel1)
																.addGap(59, 59, 59).addComponent(txtReferencia,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 191,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(panelDialogoLayout.createSequentialGroup()
										.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))
						.addGap(210, 210, 210)));
		panelDialogoLayout.setVerticalGroup(panelDialogoLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDialogoLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(txtReferencia,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel10).addComponent(txtCantidad,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(21, 21, 21)
						.addGroup(panelDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel7).addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(txtTela, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnAgregar)
						.addGap(22, 22, 22)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(panelDialogo,
						javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0,
								0, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelDialogo,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			verificarCampos();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage() );
			return;
		}
		String ref = txtReferencia.getText().trim().toUpperCase(), nombre = txtNombre.getText().trim(),
				marca = txtMarca.getText().trim(), talla = txtTalla.getText().trim(), color = txtColor.getText().trim(),
				tela = txtTela.getText().trim();
		double precioCompra = Double.parseDouble(txtPrecioCompra.getText().trim()),
				precioVenta = Double.parseDouble(txtPrecioVenta.getText().trim());
		int cantidad = Integer.parseInt(txtCantidad.getText().trim());
		try {
			if(talla.isEmpty())talla =null;
			if(tela.isEmpty())tela=null;
			if(color.isEmpty())color=null;
			principal.controller.agregarProducto(ref, nombre, precioVenta, precioCompra, marca, talla, color, tela,
					cantidad);
			this.dispose();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}
	}

	
	private void verificarCampos() throws Exception {
		String ref = txtReferencia.getText().trim().toUpperCase(), nombre = txtNombre.getText().trim(),
				marca = txtMarca.getText().trim(), talla = txtTalla.getText().trim(), color = txtColor.getText().trim(),
				tela = txtTela.getText().trim(), precioCompra = txtPrecioCompra.getText().trim(),
				precioVenta = txtPrecioVenta.getText().trim(), cantidad = txtCantidad.getText().trim();
		if (ref.isEmpty() || nombre.isEmpty() || precioCompra.isEmpty()|| precioVenta.isEmpty()|| marca.isEmpty() || cantidad.isEmpty()) {
			throw new Exception("Por favor llene los campos marcados con *");
		}
		try {
			Double.parseDouble(txtPrecioCompra.getText().trim());
		} catch (Exception e) {
			throw new Exception("El precio de compra no es valido");
		}
		try {
			Double.parseDouble(txtPrecioVenta.getText().trim());
		} catch (Exception e) {
			throw new Exception("El precio de venta no es valido");
		}
		try {
			if (Integer.parseInt(txtCantidad.getText().trim()) <= 0)
				throw new Exception("La cantidad no puede ser menor o igual a 0");
		} catch (Exception e) {
			throw new Exception("La cantidad no es valida");
		}
		if (txtTalla.getText() == "")
			txtTalla.setText(null);
		if (txtColor.getText() == "")
			txtColor.setText(null);
		if (txtTela.getText() == "")
			txtTela.setText(null);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DialogoAgregarProducto.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DialogoAgregarProducto.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DialogoAgregarProducto.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogoAgregarProducto.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DialogoAgregarProducto dialog = new DialogoAgregarProducto(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnAgregar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel panelDialogo;
	private javax.swing.JTextField txtCantidad;
	private javax.swing.JTextField txtColor;
	private javax.swing.JTextField txtMarca;
	private javax.swing.JTextField txtNombre;
	private javax.swing.JTextField txtPrecioCompra;
	private javax.swing.JTextField txtPrecioVenta;
	private javax.swing.JTextField txtReferencia;
	private javax.swing.JTextField txtTalla;
	private javax.swing.JTextField txtTela;
	// End of variables declaration
}
