package interfaz;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.HashMap;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import controller.ControllerBoutique;
import controller.ControllerPersistance;

/*
 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author daniel
 */
public class InterfazPrincipal extends javax.swing.JFrame {
	public ControllerBoutique controller = new ControllerBoutique(this);

	/**
	 * Creates new form InterfazPrincipal
	 */
	public InterfazPrincipal() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		// setBackground(new Color(69,90,100));
		panelPrincipal = new javax.swing.JPanel() {
			@Override
			protected void paintComponent(Graphics g) {
				Dimension tamanio = getSize();
				ImageIcon i = new ImageIcon("./data/images/background.jpg");
				g.drawImage(i.getImage(), 0, 0, tamanio.width, tamanio.height, null);
				setOpaque(false);
				super.paintComponent(g);
			}
		};

		btnInventario = new javax.swing.JButton();
		btnAgregar = new javax.swing.JButton();
		btnVender = new javax.swing.JButton();
		btnReportes = new javax.swing.JButton();
		btnAgregarSalida = new javax.swing.JButton();
		btnPagar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Boutique");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setLocationByPlatform(true);
		setName("framePrincipal"); // NOI18N
		setResizable(false);
		btnInventario.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		btnInventario.setIcon(new ImageIcon(new ImageIcon(".\\data\\images\\icons\\inventario-icon.png").getImage()
				.getScaledInstance(60, 60, Image.SCALE_DEFAULT))); // NOI18N
		btnInventario.setToolTipText("Inventario");
		btnInventario.setOpaque(false);
		btnInventario.setForeground(Color.WHITE);
		btnInventario.setContentAreaFilled(false);
		btnInventario.setBorderPainted(false);
		btnInventario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnInventarioActionPerformed(evt);
			}
		});

		labFondo = new javax.swing.JLabel();
		labFondo.setIcon(new ImageIcon(new ImageIcon(".\\data\\images\\fondo-image.png").getImage()
				.getScaledInstance(400, 350, Image.SCALE_DEFAULT)));
		btnAgregar.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		btnAgregar.setIcon(new ImageIcon(new ImageIcon(".\\data\\images\\icons\\anadir-icon.png").getImage()
				.getScaledInstance(60, 60, Image.SCALE_DEFAULT))); // NOI18N
		btnAgregar.setToolTipText("Añadir un producto");
		btnAgregar.setOpaque(false);
		btnAgregar.setForeground(Color.WHITE);
		btnAgregar.setContentAreaFilled(false);
		btnAgregar.setBorderPainted(false);
		btnAgregar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAgregarActionPerformed(evt);
			}
		});

		btnVender.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		btnVender.setIcon(new ImageIcon(new ImageIcon(".\\data\\images\\icons\\vender-icon.png").getImage()
				.getScaledInstance(60, 60, Image.SCALE_DEFAULT))); // NOI18N
		btnVender.setToolTipText("Vender productos");
		btnVender.setOpaque(false);
		btnVender.setForeground(Color.WHITE);
		btnVender.setContentAreaFilled(false);
		btnVender.setBorderPainted(false);
		btnVender.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnVenderActionPerformed(evt);
			}
		});

		btnReportes.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		btnReportes.setIcon(new ImageIcon(new ImageIcon(".\\data\\images\\icons\\reporte-icon.png").getImage()
				.getScaledInstance(60, 60, Image.SCALE_DEFAULT))); // NOI18N
		btnReportes.setToolTipText("Reportes");
		btnReportes.setOpaque(false);
		btnReportes.setForeground(Color.WHITE);
		btnReportes.setContentAreaFilled(false);
		btnReportes.setBorderPainted(false);
		btnReportes.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnReportesActionPerformed(evt);
			}
		});

		btnAgregarSalida.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
		btnAgregarSalida.setIcon(new ImageIcon(new ImageIcon(".\\data\\images\\icons\\salida-icon.png").getImage()
				.getScaledInstance(60, 60, Image.SCALE_DEFAULT))); // NOI18N
		btnAgregarSalida.setToolTipText("Agregar Salida de dinero");
		btnAgregarSalida.setOpaque(false);
		btnAgregarSalida.setForeground(Color.WHITE);
		btnAgregarSalida.setContentAreaFilled(false);
		btnAgregarSalida.setBorderPainted(false);
		btnAgregarSalida.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAgregarSalidaActionPerformed(evt);
			}
		});

		btnPagar.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N

		btnPagar.setIcon(new ImageIcon(new ImageIcon(".\\data\\images\\icons\\pagar-icon.png").getImage()
				.getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
		btnPagar.setToolTipText("Pagar Factura");
		btnPagar.setOpaque(false);
		btnPagar.setForeground(Color.WHITE);
		btnPagar.setContentAreaFilled(false);
		btnPagar.setBorderPainted(false);
		btnPagar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPagarActionPerformed(evt);
			}

		});

		javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
		panelPrincipal.setLayout(panelPrincipalLayout);
		panelPrincipalLayout.setHorizontalGroup(
				panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout
								.createSequentialGroup().addContainerGap()
								.addGroup(panelPrincipalLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout
												.createSequentialGroup()
												.addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(labFondo, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(panelPrincipalLayout.createSequentialGroup()
												.addGap(0, 0, Short.MAX_VALUE)
												.addComponent(btnAgregarSalida, javax.swing.GroupLayout.PREFERRED_SIZE,
														117, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE,
														117, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(104, 104, 104)));
		panelPrincipalLayout.setVerticalGroup(panelPrincipalLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panelPrincipalLayout.createSequentialGroup()
										.addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 66,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 186, Short.MAX_VALUE))
								.addComponent(labFondo, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnAgregarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(30, 30, 30)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(panelPrincipal,
						javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0,
								0, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelPrincipal,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void btnPagarActionPerformed(ActionEvent evt) {
		try {
			long cedula = Long.parseLong(JOptionPane.showInputDialog("Ingrese la cedula del cliente"));
			if(!controller.existeCliente(cedula)){
				JOptionPane.showMessageDialog(this, "El cliente no existe");
				return;
			}
			
			double valor = Double
					.parseDouble(JOptionPane.showInputDialog("Ingrese el valor a pagar, actualmente este cliente debe: "
							+ controller.darCreditoCliente(cedula)));
			int i = JOptionPane.showConfirmDialog(this, "Esta seguro que desea pagar este credito?");
			if (i == JOptionPane.YES_OPTION) {
				controller.pagar(cedula, valor);

			}
		} catch (Exception e) {

		}

	}

	private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {
		new DialogoInventario(this, rootPaneCheckingEnabled).setVisible(true);
	}

	private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {
		new DialogoAgregarProducto(this, rootPaneCheckingEnabled).setVisible(true);
	}

	private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {
		new DialogoVender(this, rootPaneCheckingEnabled).setVisible(true);
	}

	private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {
		new DialogoReporte(this, rootPaneCheckingEnabled).setVisible(true);
	}

	private void btnAgregarSalidaActionPerformed(java.awt.event.ActionEvent evt) {
		int i = JOptionPane.showConfirmDialog(this, "Desea agregar una nueva salida de dinero?");
		if (i == JOptionPane.YES_OPTION) {
			String causa = JOptionPane.showInputDialog("Ingrese el nombre del concepto de la salida de dinero");
			double monto = Double
					.parseDouble(JOptionPane.showInputDialog("Ingrese el monto por el cual se registra esta salida"));
			controller.registrarSalida(causa, monto);
			JOptionPane.showMessageDialog(this, "Salida: " + causa + " por " + monto + ", agregada correctamente");
		}
	}

	public void dispose() {
		new ControllerPersistance(controller.darMundo()).guardarInfo();
		super.dispose();
		System.exit(0);
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnAgregar;
	private javax.swing.JButton btnInventario;
	private javax.swing.JButton btnReportes;
	private javax.swing.JButton btnVender;
	private javax.swing.JPanel panelPrincipal;
	private javax.swing.JButton btnAgregarSalida, btnPagar;
	private JLabel labFondo;

	// End of variables declaration
	public int buscarItem(String ref) throws Exception {
		for (int i = 0; i < controller.darInventario().size(); i++) {
			if (controller.darInventario().get(i).darReferencia().equalsIgnoreCase(ref)) {
				return i;
			}
		}
		throw new Exception("No existe un item con esa referencia en el inventario");
	}

}
